### ISSUE TITLE
BoundsError in JuMP.value.(x)

### ISSUE THREAD

**Issue by KenZhenLin** [JuliaOpt/MosekTools.jl#51] opened 2020-04-21 16:44 UTC
Here is a simple example to illustrate the error:
```julia
using Mosek, MosekTools, JuMP, LinearAlgebra, Random, Gurobi
M = Model(with_optimizer(Mosek.Optimizer))
@variable(M, x[1:10])
@variable(M, t)
@constraint(M, x[1:2].>=0)
@constraint(M, t>=0)
@objective(M, Min, t+x[1]+x[2])
optimize!(M)
```
Now I want to get the optimal value of `x` by `JuMP.value.(x)`, I will get the error: `BoundsError: attempt to access 3-element Array{Float64,1} at index [4]`.

This issue doesn't happen with Gurobi.Optimizer, and can also be fixed by changing `@constraint(M, x[1:2].>=0)` to `@constraint(M, x[1:10].>=0)`.

I'm guessing this is happening because the variables `x[3:10]` are unused. But what if I still want to get the optimal values for x[1] and x[2]? 
With Gurobi, I can simply do JuMP.value.(x) and all the unused components in x will be replaced with 0. But it looks like Mosek can't do this.

Thank you!

**Comment by blegat** [comment] 2020-04-21 21:10
Thanks for reporting this issue. It seems to be a duplicate of https://github.com/JuliaOpt/MosekTools.jl/issues/43

**Closed** 2020-04-21 21:11 UTC
Labels: duplicate
